OWASP_TOP10_SCENARIOS = [
    {
        "id": "a01",
        "code": "A01",
        "title": "Broken Access Control",
        "summary": "사용자 권한 경계가 무너질 때 발생하는 문제를 점검한다.",
        "service_case": "일반 사용자가 관리자 페이지나 타인 리소스에 접근 가능한지 확인",
        "checkpoints": [
            "비로그인 사용자의 보호 페이지 접근 차단",
            "일반 사용자의 /admin 접근 차단",
            "타인 게시물/민원 수정 및 조회 차단",
        ],
        "mitigations": [
            "모든 수정/삭제 라우트에 서버 측 권한 검증 적용",
            "리소스 소유권 체크와 역할(role) 체크를 분리해 적용",
            "권한 실패를 감사 로그로 기록",
        ],
    },
    {
        "id": "a02",
        "code": "A02",
        "title": "Cryptographic Failures",
        "summary": "암호화 및 비밀값 관리 부실로 데이터가 노출될 가능성을 점검한다.",
        "service_case": "시크릿/DB 비밀번호 하드코딩, 평문 민감정보 노출 여부 점검",
        "checkpoints": [
            "SECRET_KEY/DB 비밀번호를 환경변수로 주입하는지 확인",
            "비밀번호 해시 저장 여부 확인",
            "민감 데이터 로그 출력 여부 점검",
        ],
        "mitigations": [
            "시크릿 관리 도구 또는 배포 환경 변수 사용",
            "비밀번호는 해시 저장(평문 금지)",
            "민감 필드 마스킹 로깅 적용",
        ],
    },
    {
        "id": "a03",
        "code": "A03",
        "title": "Injection",
        "summary": "SQL/명령/템플릿 인젝션 가능 지점을 식별한다.",
        "service_case": "검색·필터 파라미터가 쿼리에 안전하게 전달되는지 검증",
        "checkpoints": [
            "ORM 파라미터 바인딩 사용 여부",
            "동적 문자열 결합 쿼리 사용 금지",
            "입력값 길이·형식 검증 적용",
        ],
        "mitigations": [
            "파라미터화된 쿼리 사용",
            "입력 검증 레이어 공통화",
            "위험 문자열 탐지 로그 추가",
        ],
    },
    {
        "id": "a04",
        "code": "A04",
        "title": "Insecure Design",
        "summary": "설계 단계에서의 보안 요구 누락을 식별한다.",
        "service_case": "민원 처리 흐름에 승인·검증 단계가 빠져 있는지 점검",
        "checkpoints": [
            "관리자 전용 프로세스의 다단계 검증 여부",
            "비정상 흐름(직접 URL 접근) 처리 여부",
            "오류/예외 플로우에서 정보 노출 여부",
        ],
        "mitigations": [
            "업무 규칙 기반 상태 전이 정의",
            "위협 모델링 기반 설계 리뷰",
            "권한/상태 전이 테스트 케이스 유지",
        ],
    },
    {
        "id": "a05",
        "code": "A05",
        "title": "Security Misconfiguration",
        "summary": "잘못된 기본 설정과 운영 설정 누락을 점검한다.",
        "service_case": "디버그 설정, 기본 계정, 과도한 에러 메시지 노출 여부 점검",
        "checkpoints": [
            "디버그 모드 비활성화",
            "기본 계정 강제 변경 정책",
            "에러 페이지 표준화 적용",
        ],
        "mitigations": [
            "환경별 설정 분리",
            "초기 계정 비밀번호 변경 절차",
            "보안 헤더 및 프록시 설정 강화",
        ],
    },
    {
        "id": "a06",
        "code": "A06",
        "title": "Vulnerable and Outdated Components",
        "summary": "취약하거나 오래된 컴포넌트 사용을 점검한다.",
        "service_case": "Flask/라이브러리 버전 고정 및 점검 절차 확인",
        "checkpoints": [
            "requirements 파일 버전 고정",
            "정기 취약점 스캔 주기 수립",
            "사용하지 않는 패키지 제거",
        ],
        "mitigations": [
            "의존성 취약점 스캔 자동화",
            "분기별 업그레이드 정책",
            "SBOM 관리",
        ],
    },
    {
        "id": "a07",
        "code": "A07",
        "title": "Identification and Authentication Failures",
        "summary": "인증 절차와 세션 관리 취약점을 점검한다.",
        "service_case": "약한 비밀번호 정책, 세션 보호 설정, 로그인 시도 제한 점검",
        "checkpoints": [
            "비밀번호 최소 길이 검증",
            "로그인 실패 누적 제한 여부",
            "세션 쿠키 보호 플래그 검토",
        ],
        "mitigations": [
            "계정 잠금/지연 정책",
            "MFA 도입",
            "세션 보안 설정 강화",
        ],
    },
    {
        "id": "a08",
        "code": "A08",
        "title": "Software and Data Integrity Failures",
        "summary": "코드/데이터 무결성 검증 부족을 점검한다.",
        "service_case": "배포 아티팩트, 의존성, 시드 데이터 변경 이력 추적",
        "checkpoints": [
            "배포 단위 체크섬/서명 사용 여부",
            "중요 설정 파일 변경 이력 검토",
            "신뢰되지 않은 원본 코드 반영 금지",
        ],
        "mitigations": [
            "CI에서 아티팩트 검증",
            "릴리스 승인 프로세스",
            "변경 이력 감사 강화",
        ],
    },
    {
        "id": "a09",
        "code": "A09",
        "title": "Security Logging and Monitoring Failures",
        "summary": "탐지와 추적이 가능한 로그 체계를 점검한다.",
        "service_case": "로그인/권한변경/민원처리 로그의 저장·조회 가능 여부 확인",
        "checkpoints": [
            "핵심 액션 감사로그 기록",
            "오류 발생 시 로깅/알림 체계",
            "로그 보존 기간 정책",
        ],
        "mitigations": [
            "운영 모니터링 대시보드 연결",
            "이상 징후 알림(알림 채널 연계)",
            "로그 무결성 보장",
        ],
    },
    {
        "id": "a10",
        "code": "A10",
        "title": "Server-Side Request Forgery",
        "summary": "서버가 외부/내부 리소스를 임의 요청하지 않도록 점검한다.",
        "service_case": "URL 입력 기능 추가 시 허용 목록, 내부망 차단 규칙 검증",
        "checkpoints": [
            "내부망/메타데이터 주소 접근 차단",
            "허용 도메인 목록 기반 요청 제한",
            "리다이렉트 체인 검증",
        ],
        "mitigations": [
            "네트워크 egress 제한",
            "URL 스킴/호스트 검증",
            "요청 프록시 계층 도입",
        ],
    },
]
